# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - deploy:
          name: deploy to api.dev.doramatching.tk
          command: ssh -o "StrictHostKeyChecking no" -p 2222 pi@quycomputer.ddns.net "cd /home/pi/Documents/Test/DoraMatching-API-main; git pull; chmod +x ./circleci/setup.sh; ./circleci/setup.sh"
